### ISSUE TITLE
Implement Help UI

### ISSUE THREAD

**Issue by ACGodliman** [paulhayes/GGJ2018#6]
Thank you for choosing the Tele_Verse Education System.

To learn with Tele_Verse, simply follow these instructions:

Select the number of participants.

Have each player select their personal avatar and key in their 4 character name.

Now you’re ready to learn!

For each round 1 player will take the role of the speaker.

This player will watch the randomly selected video clip, paying careful attention to what is being spoken [they may watch a maximum of 3 times]. When they are ready, it is time to progress to the next page and repeat what they have just heard into the microphone embedded in their computer or portable telephone.

Next the other players to take it in turn to listen to this recording [as many times as they wish] and key in which words they believe are being spoken.

The video clip will then reply automatically, revealing the correct word of phrase.

The Tele_Verse Education System then scores each player based on the accuracy of their translation, or in the case of the speaking player, the comprehensibility of their repetition.

Remember to attention to the player name displayed at the top of the screen.

The number of rounds will vary according to the number of players.

Tele_Verse is a subsidiary of Happee Global Pharmaceuticals. 

If you have any complaints about the Tele_Verse Education System please write to us at:  

Tele_Verse 
Happee Global Pharmaceuticals, Building E
Downview Business Park 
Sussex
PM1 ADE8

**Comment by ACGodliman** [comment]
(this is a draft, feedback and editing welcome)

**Comment by paulhayes** [comment]
Fixed in 2cd264ba225e3ca642eb8756609db60fd6797c40
